import localFont from "next/font/local";
import { Roboto_Condensed } from 'next/font/google'


import "./globals.css";
import Header from "./components/Header";
const roboto_Condensed = Roboto_Condensed({  subsets: ['latin'] })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto_Condensed.className}`}  >
        <Header />
        {children}
      </body>
    </html>
  );
}
